### ISSUE TITLE
Support custom templates

### ISSUE THREAD

**Issue by acrookston** [dvanderbeek/magic-link#10]
Should support templates for:
- mailer
- views

This is semi-related to #9, allowing templates would allow i18n on them.

**Comment by dvanderbeek** [comment]
Have you tried placing your own views in the main app? That should take precedence over the ones in the gem.

**Comment by dvanderbeek** [comment]
I'm going to close this. I have verified that you can override the view and mailer templates by creating your own in the same directory where they are located in the gem:

`/magic/link/magic_links/new.html.erb`
`/magic/link/magic_link_mailer/send_magic_link.html.erb`
`/magic/link/magic_link_mailer/send_magic_link.text.erb`

If someone wants to create a generator to copy the default views into the host app similar to the `rails g devise:views`, that would be a welcome PR!
