### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by nmacuk** [dvanderbeek/magic-link#14]
Hello,
Can you please make a detailed documentation on how to condigure proprely this gem with devise?
I did everything that is said in README and now after clicking on a sent link I got NoMethodError "serialize_into_session', after that I got NoMethodError "authenticatable_salt". I really tried to find fix on my own but couldn't find any good way to fix that and lack of documentation is not helping.

I really like this gem, but so little of documentation is not enough, can you please do something about it?

**Comment by dvanderbeek** [comment]
I'm not sure what would be causing this issue. I just set up a new Rails 6 app with Devise 4.7.1 and installed magic-link. Everything worked for me. The only step that wasn't in the README was that you also have to install simple_form, which I'd like to remove as a dependency (or at least add it as one in the gemspec for this gem). What versions of Rails and Devise are you using?

**Comment by nmacuk** [comment]
rails 6.02
activeadmin 2.7.0
devise 4.7.1

Maybe activeadmin is causing the issue? But it uses devise as a dependency

Do u perhaps want a link to my PR in order to make a code review for me and check if i correctly configured it?

**Comment by dvanderbeek** [comment]
sure, if you send a link I can try to take a quick look.

**Comment by nmacuk** [comment]
https://github.com/200/tokenowo/pull/27
There you go. Thanks in advance!

**Comment by dvanderbeek** [comment]
just commented. I don't think your issues are because of this gem. If you follow the documentation for Devise to get that set up, and then follow the README here to get magic-link set up, it should work. If there's something specific missing from the documentation here, I will be happy to add it or review a PR adding it!
