### ISSUE TITLE
Need to skip :authenticate_user!

### ISSUE THREAD

**Issue by dvanderbeek** [dvanderbeek/magic-link#6]
If you have `before_action :authenticate_user!, unless: :devise_controller?` in your application controller, users can't access the magic link pages

**Comment by dvanderbeek** [comment]
also probably need to add a non-authenticated route for the magic link to point at and then redirect to the desired page. right now we default to root_url and if that page is authenticated, you can't log in

**Comment by jessehanley** [comment]
Hey @dvanderbeek, we noticed after upgrading that this gem is currently broken I believe because of this issue. We're removing it for now but will monitor.

**Comment by dvanderbeek** [comment]
Hey @jessehanley thanks for letting me know. I just added a `skip_before_action` to the magic links controller and released a new version `1.1.0` - let me know if that works for you.

**Comment by jessehanley** [comment]
Thanks for shipping this quickly, @dvanderbeek 🙏 

Ran into this bug: https://stackoverflow.com/questions/41266207/before-process-action-callback-authenticate-user-has-not-been-defined/41266746

Fixed it here: https://github.com/jessehanley/magic-link/commit/0883d4e05d22e81608443f6d0d5a9562c425d04a

Thoughts?

**Comment by dvanderbeek** [comment]
@jessehanley looks good to me, want to open a PR so I can merge this and release another new version?

**Comment by jessehanley** [comment]
No worries, here ya go https://github.com/dvanderbeek/magic-link/pull/23
