### ISSUE TITLE
Is this project alive? January 2019

### ISSUE THREAD

**Issue by Alxzu** [dvanderbeek/magic-link#8]
I wasn't able to get this from rubygems.org 😞

**Comment by dvanderbeek** [comment]
@Alxzu Sorry about that, I never published the gem and have been using it my own project directly from github. I can try to release it to rubygems sometime soon. I haven't been actively working on it lately, but the core functionality seems to get the job done and contributions are always welcome!

**Comment by dvanderbeek** [comment]
after getting another request to release this on ruby gems, I finally got around to it. https://rubygems.org/gems/magic-link
